[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "uber_pipeline_orchestrator.definitions"
code_location_name = "uber_pipeline_orchestrator"